# Generated by Django 2.2 on 2019-04-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('result', models.CharField(choices=[('W', 'W'), ('B', 'B'), ('D', 'D')], max_length=1)),
                ('age_category', models.CharField(choices=[('Under 20', 'Under 20'), ('Under 30', 'Under 30'), ('Under 40', 'Under 40'), ('Under 50', 'Under 50'), ('OPEN', 'OPEN')], max_length=1)),
                ('black_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_black', to='chess.ChessPlayer')),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_white', to='chess.ChessPlayer')),
            ],
        ),
    ]
